CBVProject/urls.py
from django.contrib import admin
from django.urls import path,include
from cbv_app import views
urlpatterns = [
    path('', views.IndexView.as_view()),
    path('cbv_app/', include('cbv_app.urls', namespace='cbv_app')),
    path('admin/', admin.site.urls),
]

cbv_app/urls.py
from django.urls import path
from cbv_app import views

app_name = 'cbv_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.SchoolDeleteView.as_view(), name='delete'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
]

cbv_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    address = models.CharField(max_length=256)

    def get_absolute_url(self):
        return reverse("cbv_app:detail", kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    major = models.CharField(max_length=256)
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

cbv_app/views.py
from django.shortcuts import render
from django.views.generic import (View, TemplateView, ListView, DetailView,
                                  CreateView, UpdateView, DeleteView)
from . import models
from django.urls import reverse_lazy
# Create your views here.

"""
TemplateView Example:
"""


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['admin_input'] = "Admin wants to say Hello"
        return context


"""
ListView Example:
"""


class SchoolListView(ListView):
    # You can manually return a context like this:
    context_object_name = "schools"
    # Or this will covert the School model to become a tag named school_list
    model = models.School


"""
DetailView Example:
"""


class SchoolDetailView(DetailView):
    # You can manually return a context like this:
    context_object_name = "schools"
    id = "pk"
    # Or this will covert the School model to become a tag named school
    model = models.School
    template_name = 'cbv_app/school_detail.html'


"""
Schools creation
"""


class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'address')
    model = models.School


"""
Schools update
"""


class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School


"""
School deletion
"""


class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy('cbv_app:list')

cbv_app/templates/cbv_app/layout_cbv_app.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Layout</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'cbv_app:list' %}">Schools</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
{#        <a class="nav-item nav-link" href="{% url 'my_simple_website:register' %}">Register</a>#}
    </div>
</nav>

</nav>
<div class="select2-container">
{% block body_block %}

{% endblock %}
</div>
</body>
</html>

cbv_app/templates/cbv_app/school_confirm_delete.html
{% extends 'cbv_app/layout_cbv_app.html' %}
{% block body_block %}
    <h1>You are going to delete {{ school.name }}?</h1>
    <form method="post">
        {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'cbv_app:detail' pk=school.pk %} ">Cancel</a>
    </form>
{% endblock %}

cbv_app/templates/cbv_app/school_detail.html
{% extends 'cbv_app/layout_cbv_app.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Welcome to school details view</h1>
        <h2> School details:</h2>
        <p>Name: {{ schools.name }}</p>
        <p>Principal: {{ schools.principal }}</p>
        <p>School's Address: {{ schools.address }}</p>
        <h3>Students:</h3>
        {% for student in schools.students.all %}
            <p>{{ student.name }} who is {{ student.age }} years old</p>
        {% endfor %}
    </div>

    <div class="select2-container">
    <p>
        <a class="btn btn-warning" href="{% url 'cbv_app:update' pk=schools.pk %}">Update</a>
        <a class="btn btn-danger" href="{% url 'cbv_app:delete' pk=schools.pk %}">Delete</a>

    </p>

    </div>
{% endblock %}

cbv_app/templates/cbv_app/school_form.html
{% extends 'cbv_app/layout_cbv_app.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h1>
            {% if not form.instance.pk %}
                Creating a School:
            {% else %}
                Updating School Info:
            {% endif %}
        </h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="submit">
            <a href="{% url 'cbv_app:list' %}" class="button">Cancel</a>
        </form>
    </div>
{% endblock %}

cbv_app/templates/cbv_app/school_list.html
{% extends 'cbv_app/layout_cbv_app.html' %}
{% block body_block %}
    <h1>Welcome to school list</h1>
    <ol>
        {% for school in schools %}
            <h2><li><a href="{{ school.id }}">{{ school.name }}</a></li></h2>
        {% endfor %}
    </ol>
    <a class="btn btn-success" href="{% url 'cbv_app:create' %}">Create</a>
{% endblock %}

templates/index.html
{% extends "layout.html" %}
{% block body_block %}
    <div class="jumbotron">
       <H1>Home Page!</H1>
    </div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Layout</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'cbv_app:list' %}">Schools</a>
        <a class="navbar-brand" href="{% url 'cbv_app:detail' %}">School Details</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
{#        <a class="nav-item nav-link" href="{% url 'my_simple_website:register' %}">Register</a>#}
    </div>
</nav>

</nav>
<div class="select2-container">
{% block body_block %}

{% endblock %}
</div>
</body>
</html>